### ISSUE TITLE
Conda Forge

### ISSUE THREAD

**Issue by thewchan** [pirxthepilot/wtfis#12]
Hello! I have successfully put this package on to Conda Forge, and I am extending the invitation for the owner/maintainers of this package to be maintainers on Conda Forge as well. Let me know if you are interested! Thanks.
https://github.com/conda-forge/wtfis-feedstock

**Comment by pirxthepilot** [comment]
Hi @thewchan this is awesome, thanks! I am not familiar with how conda forge packaging works but happy to help out!

**Comment by thewchan** [comment]
@pirxthepilot Great, I can add you as a maintainer. There is very little work involved as the bots will make a PR whenever a new version is pushed to PyPI upstream, all we need to do is to check to see all tests pass and merge the PR, and modify the recipe if tests fail. It should be quite self explanatory!

**Comment by pirxthepilot** [comment]
got it @thewchan , thank you!
