### ISSUE TITLE
Bug: In the whois ui, newly registered/updated fields show up as unix epoch times

### ISSUE THREAD

**Issue by rxxsta** [pirxthepilot/wtfis#14]
![image](https://user-images.githubusercontent.com/37952239/189276043-2c3bcfdd-cf32-4ce9-acd3-0460ec6db8bf.png)
![image](https://user-images.githubusercontent.com/37952239/189276296-92209d08-f3a2-4de3-80e3-7c285ec56f6e.png)

**Comment by pirxthepilot** [comment]
Good catch! Will fix this soon, and also the other bug you reported. Thanks!

**Comment by pirxthepilot** [comment]
@rxxsta looks like this bug is on the Passivetotal side :/

![image](https://user-images.githubusercontent.com/7690118/189283627-c70159f3-8eea-4d7e-bf37-396094341f75.png)

https://community.riskiq.com/search/crankdiato.discount/whois

**Comment by rxxsta** [comment]
Using https://whoisjson.com/
Interesting that their fields appear null too
![image](https://user-images.githubusercontent.com/37952239/189289045-9e787428-6e85-4d81-ad07-f06bf4f0a7fe.png)

**Comment by pirxthepilot** [comment]
From lookup.icann.org:

Registry Server URL: https://rdap.donuts.co/rdap/domain/crankdiato.discount
Registrar Server URL: https://rdap.tldregistrarsolutions.com//domain/crankdiato.discount

The dates look OK on the registry URL, and broken on the registrar URL. Though in the latter, the expiration date is broken too..

**Comment by rxxsta** [comment]
I think this can be closed, this isn't really issue from wtfis side. I tested another newly created domain that didn't have this issue.
