### ISSUE TITLE
RiskIQ / Passivetotal does not work anymore

### ISSUE THREAD

**Issue by MichaelSchreiner** [pirxthepilot/wtfis#20]
RiskIQ has been bought by Microsoft, the login creation has been shut down and replaced by "Defender Threat Intelligence". Old logins are supposed to still work via API. Is there an alternative?

**Comment by pirxthepilot** [comment]
Ah, that's too bad. Let me see what can be done here. Thanks for the heads up!

**Comment by plehr** [comment]
Hi @MichaelSchreiner & @pirxthepilot,
MS bought RiskIQ but you can still register with this (hidden) link: https://community.riskiq.com/registration/wtfis
This is not a solution for the future, but OK for now...

**Comment by pirxthepilot** [comment]
Still can't find a viable whois alternative that has a free tier. Any recommendations?

**Comment by pirxthepilot** [comment]
Latest version (v0.4.0) (PR #31) adds an additional whois source (ip2whois.com) which offers 500 free queries per month. I find the data isn't as good as PT but it's better than what VT provides. I will keep looking for more quality whois sources.

Closing this issue but please create a new one if you have recommendations / ideas. Thanks!
