### ISSUE TITLE
VirusToal Quota to low, makes wtfis unusable

### ISSUE THREAD

**Issue by ThomasCr** [pirxthepilot/wtfis#26]
A quota from 1 query per day from Virustotal, just kills this project. It is also not enough, to complete **-1-** query with this tool.

```
$ wtfis adomain.com
⠙ Fetching data from Virustotal ━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━  66% 0:00:00
Error fetching data: 429 Client Error: Too Many Requests for url: https://www.virustotal.com/api/v3/domains/adomain.com/resolutions
```

It would be nice, if this can be changed in any way (skip virustotal or make only one query per wtfis call, or...)

**Comment by pirxthepilot** [comment]
Hi @ThomasCr , that's interesting, I never had that issue with my free tier account. Looking at it now, these are my quotas:

```
Request rate	4 lookups / min
Daily quota	500 lookups / day
Monthly quota	15.50 K lookups / month
```

May be worth contacting VT about it?

But also good point about being able to skip VT. At the moment wtfis is heavily reliant on it but I will make a note to make it less so eventually. This requires non-trivial refactoring so it might take a while.

**Comment by ThomasCr** [comment]
Thats my VT quotas ![]()

**Comment by pirxthepilot** [comment]
Closing as it does not look like a wtfis issue. However, I created #32 to let wtfis continue even if VT resolution fails.
