### ISSUE TITLE
Maybe it would be nice, to also query RBL lists 

### ISSUE THREAD

**Issue by ThomasCr** [pirxthepilot/wtfis#27]
Hi,

it would be nice, to qeury also RBL Lists. Like the one from Spamhouse ans so one...
They and others have a ip/url blocklist. We could display, if the target ip is from a dynamic address pool or used in a botnet and so on...

**Comment by pirxthepilot** [comment]
I think VT and Shodan in some way provides this info, probably not comprehensive, but I am also currently exploring more sources for enrichment which hopefully provide better coverage. Stay tuned!
