### ISSUE TITLE
Fail open on VT resolution errors

### ISSUE THREAD

**Issue by pirxthepilot** [pirxthepilot/wtfis#32]
Let processing continue if the VT resolutions call fails for any reason.

Tangential to #26 .

**Comment by wech71** [comment]
This is important, as VT seems to have lowered the limits for new accounts to 1 request per minute instead of previous 4. At least my api key has the following limits, which makes wtfis always bail out on the first try.

Request rate | 1 lookups / min
1 lookups / day
31 lookups / month

**Comment by pirxthepilot** [comment]
@wech71 oh wow, that's rough. Didn't know the limit gets that low... 1 lookup/day seems too harsh.

Thanks for letting me know, will definitely work on this one next.

**Comment by pirxthepilot** [comment]
Addressed by #36 which is included in latest 0.5.0 release.

**Comment by wech71** [comment]
Just for the record:

I created a new virus total account recently and now the limits are pretty generous

Request rate | 4 lookups / min
500 lookups / day
15.5 K lookups / month

Maybe there was some problem creating my older account, which I now have deleted (it still had the 1 Lookups per day limit)

**Comment by pirxthepilot** [comment]
@wech71 thanks for the update! Interesting that the limits are attached to the account.

**Comment by pirxthepilot** [comment]
Hi @notDavid , that is correct, a VT key is still a requirement as this tool was originally written primarily to get VT data. However, I've been thinking about eventually not requiring VT since it already supports quite a few other sources.
