### ISSUE TITLE
How do I upgrade?

### ISSUE THREAD

**Issue by zell-mbc** [pirxthepilot/wtfis#35]
I tried "pip install wtfis" and "pip uninstall wtfis" but always end up with v.0.2.2

**Comment by pirxthepilot** [comment]
Hi @zell-mbc , that's interesting, have you also tried `pip install -U wtfis` ?

**Comment by zell-mbc** [comment]
Ha, that did the trick. Clearly I am no Python expert :-)
Thanks for helping along.
