### ISSUE TITLE
Docker Image?

### ISSUE THREAD

**Issue by technicalguru** [pirxthepilot/wtfis#39]
Can you provide a Docker image for this tool? It could make the installation much easier.

**Comment by pirxthepilot** [comment]
@technicalguru sounds like a good idea. I will find time to do this. Thanks!

**Comment by pirxthepilot** [comment]
Just merged #40. @technicalguru this adds the ability to build a local docker image and run wtfis from there. Do test when you get the chance, and feel free to open a new issue if you encounter any problems. Thanks!

I might eventually host the image in dockerhub or ghcr, but for now I'd like it to be hosted on as few locations as possible to reduce potential attack surfaces (i.e. supply chain).
