### ISSUE TITLE
Gateway Time-out for riskiq.net 

### ISSUE THREAD

**Issue by presianbg** [pirxthepilot/wtfis#46]
Hi,

Looks like Microsoft killed the riskIQ portal completely:

![image](https://user-images.githubusercontent.com/2163486/225548028-f332aa6e-b6f6-44fc-91e9-d2f578385edb.png)

The plugin is not functional :(

Cheers,
PY

**Comment by ehjmx** [comment]
It is working if you use this [link](https://community.riskiq.com/registration/). At least I needed to be patient as the first three attempts I tried to register failed at various points but in the end I could register successfully.
Fingers crossed that the author of this tools finds a viable solution as the temporary one in issue #25 is not able to gather information from .de domains which is unfortunate as I'm based in Germany.

**Comment by pirxthepilot** [comment]
@ehjmx thanks for sharing that link, hope the signup still works. Still no luck with .de domains - unfortunately, even the alternate whois provider I found (ip2whois) does not support it.
