### ISSUE TITLE
Feature request: support direct query of IP addresses

### ISSUE THREAD

**Issue by bill-e-ghote** [pirxthepilot/wtfis#5]
WHOIS can be queried using IP addresses. It would be nice for wtfis to model this functionality. As an extension, possibly add support for querying AS names or numbers.

**Comment by pirxthepilot** [comment]
@bill-e-ghote I plan to implement this in a near-future version. Very useful for sure!

**Comment by daga480** [comment]
Being able to use CIDR notation, wildcards, and/or human readable ranges (1.1.1.1-4) for IP lookups could be helpful

**Comment by pirxthepilot** [comment]
@daga480 having an IP range could potentially eat up API call limits (whether by accident or not), but I will think more about it. Thanks for the idea!
